### PR TITLE
Follow the law and use the original license

### PR DESCRIPTION
**Pull request by S-B99**
As this code is based off of https://github.com/zeroeightysix/KAMI, you must use the original license or ask for permission from 086 and all the contributors in order to change the license.

### CODE REVIEW

**Comment by CrylicArk** [comment]
screw the law

**Comment by S-B99** [comment]
The repo can be dmca'd if it doesn't follow the license properly.

**Comment by CrylicArk** [comment]
yes but fuck the law anyways

**Comment by S-B99** [comment]
I agree with you, but unfortunately you need to follow the law in this society, especially if you're publishing a modified version of someone elses work.

**Comment by FINZ0** [comment]
just one small detail it's not based on kami

**Comment by S-B99** [comment]
It clearly is originally from KAMI. The structure is identical, along with the naming scheme.

**Comment by CrylicArk** [comment]
its a fucking joke i follow the law

**Comment by S-B99** [comment]
Please tell me how this is just the rearranged KAMI Module class, along with a ton of others, and the same naming scheme as KAMI, and the exact same package structure as KAMI. 
https://github.com/FINZ0/Osiris/blob/37069aae0833a2f7e8c058322cd778099c2043cd/src/main/java/me/finz0/osiris/module/Module.java
https://github.com/S-B99/kamiblue/blob/5187b4e/src/main/java/me/zeroeightsix/kami/module/Module.java

**Comment by S-B99** [comment]
Don't even try denying it, this is a modified fork of [zeroeightysix/KAMI](https://github.com/zeroeightysix/KAMI)

https://github.com/FINZ0/Osiris/blob/31acd84f27f7bb1083348bf789c8ca7140356532/src/main/java/me/finz0/osiris/OsirisMod.java
https://github.com/zeroeightysix/KAMI/blob/f730ad10db660e7c6e241a58574dafd0cb727f17/src/main/java/me/zeroeightsix/kami/KamiMod.java

**Comment by S-B99** [comment]
I don't see the point of denying that it's a KAMI fork, this pull request is just to resolve any legal issues that you would have by changing the license illegally to GPLv3

**Comment by cookiedragon234** [comment]
Regardless of your disrespect towards the law, surely you respect the amount of effort that 086 has put into kami? Do you not want to appreciate his only request in return for him providing all his work open source and free?

How would you feel if someone skidded your code, uploaded it to github, and provided zero credit or acknowledge of the original developer.

**Comment by S-B99** [comment]
> How would you feel if someone skidded your code, uploaded it to github, and claimed it was their work
ftfy

**Comment by Crystallinqq** [comment]
I agree with Bella and cookie. it still uses code from kami therefore you should just approve the PR

**Comment by Crystallinqq** [comment]
> not kami
https://github.com/zeroeightysix/KAMI/tree/f730ad10db660e7c6e241a58574dafd0cb727f17/src/main/java/me/zeroeightsix/kami/gui/font https://github.com/FINZ0/Osiris/tree/31acd84f27f7bb1083348bf789c8ca7140356532/src/main/java/me/finz0/osiris/util/font

**Comment by zeroeightysix** [comment]
Thanks!

**Comment by r33666** [comment]
> I agree with you, but unfortunately you need to follow the law in this society, especially if you're publishing a modified version of someone elses work.

yo how bout you suck a dick. kami blue sucks shit compared to Osiris. You should be respecting this man for helping you come to the conclusion of how shit your client is and that you need to make something half decent to compete. Hoes mad stfu stay mad ree

**Comment by r33666** [comment]
> I don't see the point of denying that it's a KAMI fork, this pull request is just to resolve any legal issues that you would have by changing the license illegally to GPLv3

like if I were you I'd just delete your client already. 🔫 🤠  hoes mad

**Comment by S-B99** [comment]
https://help.github.com/en/github/site-policy/github-event-code-of-conduct

**Comment by cookiedragon234** [comment]
rofl

**Comment by vlakreeh** [comment]
Wow, this code is skidded trash. Nice to see that Hal's CFont is still being skidded a whole half decade after it was written.

**Comment by r33666** [comment]
> Wow, this code is skidded trash. Nice to see that Hal's CFont is still being skidded a whole half decade after it was written.

*me and the homies tryna find who the fuck asked*

**Comment by r33666** [comment]
> https://help.github.com/en/github/site-policy/github-event-code-of-conduct

*hoes mad that dev bossman made better cheat. replies my censoring my ass to hide the *TROOF* that your client a useless compilation of gobildigook the masses don't even know how hard dey be being manipoolaided by this mf. TLDR fuck the man, hoes mad*

**Comment by vlakreeh** [comment]
@r33666 made a better cheat? It's hardly making something if you are just skidding together other people's code.

**Comment by S-B99** [comment]
> putting a thumbs up on your own comments

Also, can you not necro old pulls which have already been merged with completely unrelated topics? You're a really low effort troll and honestly I feel you're just mad I banned you from my repo.

**Pull request merged**
